### ISSUE TITLE
Can't build the package with sbt 0.13.5

### ISSUE THREAD

**Issue by nonsleepr** [dlouwers/reactive-consul#16]
`project/build.properties` specifies `sbt.version=0.13.5`.
Execution of any `sbt` command with that version results in `Error during sbt execution: No Scala version specified or detected`.

**Comment by dlouwers** [comment]
Hi, 

Cannot reproduce on my machine. Have you had alook at https://github.com/sbt/sbt/issues/1117?

**Comment by nonsleepr** [comment]
Inside and outside of the project:
```
 ~/reactive-consul $ sbt --version
Error during sbt execution: No Scala version specified or detected
 ~/reactive-consul $ sbt sbtVersion
Error during sbt execution: No Scala version specified or detected

~ $ sbt --version
[warn] The `-` command is deprecated in favor of `onFailure` and will be removed in 0.14.0
~ $ sbt sbtVersion
[info] 0.13.13
```

Looks like removing `~/.sbt/boot` _solves_ the problem, but anyway, `sbt 0.13.5` was released 3 years ago. Time to move on.

**Comment by dlouwers** [comment]
Hi, have updated the source to use 0.13.15. No idea why I still had it on that old version.
