### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by lnelsonCIG** [dlouwers/reactive-consul#17]
`libraryDependencies += "nl.stormlantern" %% "reactive-consul" % "0.2.0"`

could be changed to:

`libraryDependencies += "nl.stormlantern" %% "reactive-consul" % "0.2.1"`

so that consumers of the library don't run into the dockertestkit unresolved dependencies.

**Comment by dlouwers** [comment]
Thanks for the pointer. Updated for latest release.
