### ISSUE TITLE
ServiceBroker should be created with unique actor name

### ISSUE THREAD

**Issue by nonsleepr** [dlouwers/reactive-consul#24]
[Hardcoded name](https://github.com/dlouwers/reactive-consul/blob/78b29df75feb00110f8fbb7b45c64237a67f9375/client/src/main/scala/stormlantern/consul/client/ServiceBroker.scala#L60) prevents the creation of multiple instances of `ServiceBroker`.

**Comment by dlouwers** [comment]
I wouldn't have thought this to be a potential issue. What scenario do you need multiple ServiceBrokers in? Simplest might be to add the option to pass a _name_ that defaults to "default".

**Comment by nonsleepr** [comment]
Can't recall exact case but I guess I had brokers for different services.

**Comment by dlouwers** [comment]
Ok, well all my constructors are convenience methods. You can easily take control like so:
```scala
def apply(systemName: String, consulAddress: URL, services: Set[ConnectionStrategy]): ServiceBroker = {
    implicit val rootActor = ActorSystem(systemName)
    val httpClient = new AkkaHttpConsulClient(consulAddress)
    ServiceBroker(rootActor, httpClient, services)
  }
```
Thank you for your feedback.

**Comment by nonsleepr** [comment]
That's what I did in the end.

**Comment by dlouwers** [comment]
Good. Do you feel that is fine or that is such a common use case there should be a special constructor for it?

**Comment by nonsleepr** [comment]
It probably is. The thing is, I followed the example to create service provider (I needed to have two providers for different services) and stumbled upon that problem.
