### ISSUE TITLE
Maven Central?

### ISSUE THREAD

**Issue by derjust** [dlouwers/reactive-consul#4]
Hi there!

Thanks for releasing this library. It solves a lot of the bread-and-butter issues without the boiler-plate-code other libraries require in the consul-scala world. Thanks again!

I see the release to Maven central - as per https://issues.sonatype.org/plugins/servlet/mobile#issue/OSSRH-16296 - seem to be in-flight since last summer. Is there any plans to complete this?
I have some experience with bringing OSS libraries to Maven Central. What's the best way to support you?
Most important question to me right now: What is the desired coordinate to be used?

**Comment by dlouwers** [comment]
Hi. 

Sorry for the late reply. Just got married and back from honeymoon :)
Yes I did indeed never get around to releasing this. I have no experience as of yet bringing projects to Maven central so any pointers would be welcome. I am likely to use "com.stormlantern" %% "reactive-consul"

**Comment by derjust** [comment]
Congratz to you, @dlouwers.
As the OSSRH already exists, how to you want to proceed? I can try to setup `build.sbt` accordingly but that would be like a guess into the blue as (right now) you are the only one who is allowed to push into that sonatype-staging repo.
Or I create an additional ticket to ask to get added to it (and after the PR is done, remove me from the project in Sonatype again.

let me know,
Sebastian

**Comment by utgarda** [comment]
I'd love to have this library in my toolbox. Please release to Maven central!

**Comment by dlouwers** [comment]
Working on it, will get it done over the weekend.

**Comment by utgarda** [comment]
@dlouwers Can I help you with that somehow, other than nudging you with comments? :)

**Comment by dlouwers** [comment]
Yes this has taken ages. Apparently a surprisingly hard thing to do in a multi module project that needs to selectively publish but one of the modules. Should be on Maven Central in a few hours.

**Comment by dlouwers** [comment]
Please skip the 0.1 version since it doesn't have a POM.
