### ISSUE TITLE
Service Tag filtering never kicks in

### ISSUE THREAD

**Issue by derjust** [dlouwers/reactive-consul#8]
The client library never applies the tag filtering:

The filtering is done, but the result is never used but the unfiltered set of `ServiceInstane`s is used:
https://github.com/dlouwers/reactive-consul/blob/e38425817dae734c4b8a35be7ce10c2f62280e4f/client/src/main/scala/stormlantern/consul/client/discovery/ServiceAvailabilityActor.scala#L32

**Comment by dlouwers** [comment]
Indeed, looks like we need to store the filtered list and use it both in updating `serviceAvailabilityState` and invoking `createServiceAvailabilityUpdate`

**Comment by dlouwers** [comment]
Should be fixed in 0.1.1-SNAPSHOT

**Comment by dlouwers** [comment]
In 0.1.1 release now.
